Merge/release 3.x
zicht/key-value-bundle pull request #39
Opened 2020-10-13 07:11 UTC by erik-zicht

2020-10-20 09:27 UTC, boudewijn-zicht requested changes

2020-10-20 09:27 UTC, boudewijn-zicht commented on src/Entity/KeyValueStorage.php
> +     * @ORM\Column(type="json_array", nullable=true)
`type="json"`, json_array is deprecated, see: https://www.doctrine-project.org/projects/doctrine-dbal/en/2.11/reference/types.html#json-array

(niet gerelateerd aan deze PR, maar zal een keer moeten, waarom niet nu?)

2020-10-20 09:27 UTC, boudewijn-zicht commented on src/Resources/config/services.xml
> +        <service alias="zicht_bundle_key_value.key_value_storage_manager" id="Zicht\Bundle\KeyValueBundle\KeyValueStorage\KeyValueStorageManagerInterface" public="true"/>
Zou hier ook graag de nieuwe naamgeving style met backwards compatability alias toepassen

2020-10-20 09:27 UTC, boudewijn-zicht commented on src/Resources/config/services.xml
> +                 id="zicht_bundle_key_value.key_value_storage_manager" public="true">
Zou hier ook graag de nieuwe naamgeving style met backwards compatability alias toepassen

2020-10-20 09:27 UTC, boudewijn-zicht commented on src/Resources/views/DataCollector/template.html.twig
> +                <td>{{ dump(value) }}</td>
Dit lijkt niet achter een `if app.debug` te zitten, en `dump` is volgens mij alleen op debug omgevingen beschikbaar...

2020-10-20 13:32 UTC, erik-zicht commented on src/Resources/views/DataCollector/template.html.twig
> +                <td>{{ dump(value) }}</td>
Dat is geen probleem, DataCollectors draaien ook alleen op debug-omgevingen, die verzorgen de informatie van de Symfony-toolbar.

2020-10-21 06:18 UTC, boudewijn-zicht approved these changes

2020-10-21 06:18 UTC, merged